//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaClinicaVivaEstetica.Dominio.Mensagens
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensGerais
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensGerais()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgendaClinicaVivaEstetica.Dominio.Mensagens.MensagensGerais", typeof(MensagensGerais).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a criação do banco de dados..
        /// </summary>
        public static string MSG0001
        {
            get
            {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A marcação só deve ser feita entre as 8hs e as 16hs..
        /// </summary>
        public static string MSG0002
        {
            get
            {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo nome é de preenchimento obrigatório..
        /// </summary>
        public static string MSG0003
        {
            get
            {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo documento é de preenchimento obrigatório..
        /// </summary>
        public static string MSG0004
        {
            get
            {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo celular é de preenchimento obrigatório..
        /// </summary>
        public static string MSG0005
        {
            get
            {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
    }
}
